services:
  pong:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pong
    restart: unless-stopped
    environment:
      - PORT=3001
      - NODE_PATH=./dist
      - NODE_ENV=production
      - DOMAIN=${DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pong.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.pong.tls=true"
      - "traefik.http.routers.pong.tls.certresolver=letsencrypt"
      - "traefik.http.services.pong.loadbalancer.server.port=3001"
      - "traefik.http.middlewares.pong-websocket.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.pong.middlewares=pong-websocket"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
