version: "3.7"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: "${CONTAINER_NAME}_node"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: node dist/index.js
    restart: unless-stopped
