name: Deploy

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
  # update_ssh:
  #   name: Telling DigitalOcean server to update
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: executing remote ssh commands
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         port: ${{ secrets.PORT }}
  #         key: ${{ secrets.SSHKEY }}
  #         script: |
  #           cd pong
  #           git reset --hard origin/master
  #           git pull origin master
  #           docker compose stop
  #           docker compose build --no-cache
  #           docker compose up -d --force-recreate
