name: Deploy

on:
  push:
    branches:
      - master

jobs:
  push_to_docker_hub:
    name: Build and push docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build images
        run: docker compose build --no-cache
      - name: Docker compose push
        run: docker compose push
  # update_ssh:
  #   name: Telling DigitalOcean server to update
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: executing remote ssh commands
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         port: ${{ secrets.PORT }}
  #         key: ${{ secrets.SSHKEY }}
  #         script: |
  #           cd pong
  #           git reset --hard origin/master
  #           git pull origin master
  #           docker compose stop
  #           docker compose build --no-cache
  #           docker compose up -d --force-recreate
